runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.app

- url: /profile/.*
  script: main.app
  login: required

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: MySQLdb
  version: "latest"
      #
# [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: gnarly-db
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: gurka
# [END env_variables]
